[GoogleSheets]
#id_spreadsheet = 1ZCnISAgw_XS7B0QHRbmJAIZC5q8RbS3VuYk7XRAkZSI

id_spreadsheet = 1-NTvWqIKwqjEkUMHVL6ubhx_x9TiPwqxsXD7kZSS3WU
sap_task_sheet = data
desc_task_sheet = description
guide_sheet = guide

